spring.application.name=backend

# Supabase PostgreSQL Connection (Transaction Pooler)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?user=postgres.dfukzpcedqgotfebykzv&password=0330-yelsha&pgbouncer=true
spring.datasource.username=postgres.dfukzpcedqgotfebykzv
spring.datasource.password=0330-yelsha
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Disable prepared statements (required for Supabase Transaction Pooler)
spring.datasource.hikari.connection-init-sql=SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=true

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Server
server.port=8080

# Supabase API
supabase.url=https://dfukzpcedqgotfebykzv.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmdWt6cGNlZHFnb3RmZWJ5a3p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDcyMTk2NzcsImV4cCI6MjAyMjc5NTY3N30.FycnpreWJ1aXFmem5

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sonephoenix46@gmail.com
spring.mail.password=qzuayprdlddlqxpt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true